# CSP compliance audit.
#
# CLAUDE.md mandates: no inline styles, scripts, or event handlers — all CSS in
# app/assets/stylesheets, all JS in app/javascript, interactivity via Stimulus
# data-action. This task scans the view layer for violations of that rule.
#
# Legacy debt exists, so the gate is incremental: csp:report fails only on
# violations NOT already recorded in the committed baseline (config/csp_baseline.txt).
# This lets CI/pre-commit block NEW violations today while the existing ones are
# burned down over time. Regenerate the baseline with csp:baseline.
#
#   bin/rails csp:report            # fail on new violations (CI / pre-commit gate)
#   bin/rails csp:report STRICT=1   # report every violation, ignore baseline
#   bin/rails csp:baseline          # snapshot current violations as accepted baseline

module CspAudit
  # label => regex. Each matches a literal inline-CSP violation in markup.
  CHECKS = {
    "inline style attribute" => /\bstyle\s*=\s*["']/,
    "<style> block"          => /<style[\s>]/i,
    "inline event handler"   => /\son[a-z]+\s*=\s*["']/i,
    "javascript: URL"        => /["']javascript:/i,
    # <script ...> opening tag with no src= → inline script
    "inline <script>"        => /<script(?![^>]*\bsrc\s*=)[^>]*>/i
  }.freeze

  SCAN_GLOBS = [
    "app/views/**/*.erb",
    "app/views/**/*.html",
    "app/components/**/*.erb"
  ].freeze

  BASELINE_PATH = "config/csp_baseline.txt".freeze

  module_function

  # Stable signature that survives line-number churn: file | label | code snippet.
  def signature(v)
    "#{v[:file]}|#{v[:label]}|#{v[:snippet]}"
  end

  def scan
    root = Rails.root
    files = SCAN_GLOBS.flat_map { |g| Dir[root.join(g)] }.uniq.sort
    violations = []

    files.each do |path|
      File.foreach(path).with_index(1) do |line, lineno|
        CHECKS.each do |label, pattern|
          next unless line.match?(pattern)

          violations << {
            file: path.sub("#{root}/", ""),
            line: lineno,
            label: label,
            snippet: line.strip[0, 120]
          }
        end
      end
    end

    [ violations, files.size ]
  end

  def load_baseline
    path = Rails.root.join(BASELINE_PATH)
    return nil unless File.exist?(path)

    File.readlines(path, chomp: true).reject { |l| l.strip.empty? || l.start_with?("#") }.to_set
  end
end

namespace :csp do
  desc "Audit views for CSP violations; fail on any NOT in the baseline"
  task report: :environment do
    violations, file_count = CspAudit.scan
    strict = ENV["STRICT"] == "1"
    baseline = strict ? Set.new : (CspAudit.load_baseline || Set.new)

    flagged = violations.reject { |v| baseline.include?(CspAudit.signature(v)) }

    grandfathered = violations.size - flagged.size
    suffix = grandfathered.positive? ? " (#{grandfathered} baselined)" : ""

    if flagged.empty?
      puts "✅ CSP: no new inline style/script/event-handler violations in #{file_count} view files#{suffix}."
      next
    end

    puts "❌ CSP: #{flagged.size} new violation(s)#{suffix}:\n\n"
    flagged.group_by { |v| v[:file] }.each do |file, vs|
      puts file
      vs.each { |v| puts "  #{v[:line]}: [#{v[:label]}] #{v[:snippet]}" }
      puts ""
    end
    puts "Fix: move CSS to app/assets/stylesheets, JS to app/javascript, use Stimulus data-action."
    puts "(If this is pre-existing debt being relocated, run `bin/rails csp:baseline` to re-snapshot.)"
    abort("CSP audit failed with #{flagged.size} new violation(s).")
  end

  desc "Snapshot current CSP violations as the accepted baseline"
  task baseline: :environment do
    violations, _ = CspAudit.scan
    signatures = violations.map { |v| CspAudit.signature(v) }.uniq.sort
    path = Rails.root.join(CspAudit::BASELINE_PATH)

    header = [
      "# CSP violation baseline — generated by `bin/rails csp:baseline`.",
      "# Pre-existing inline style/script/event-handler debt that csp:report tolerates.",
      "# Goal: burn this list down to zero. Do NOT add new entries by hand.",
      "# Format: <file>|<label>|<code snippet>"
    ]
    File.write(path, (header + signatures).join("\n") + "\n")
    puts "Wrote #{signatures.size} baselined violation(s) to #{CspAudit::BASELINE_PATH}."
  end
end
